# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a32ddaa42bb02c8c942ae92daedcb1ceaf698b6aad39008f89fdfcaa7bc81337ff9a4862b087579faf89f975e0efdfd8eef50cfee370a5451dcaf1d9a02cbf60

test:
  secret_key_base: c9a8e6b80b5bc2fdcec7d75841d73635edd77cd1adb997cf74210dcffbe0095e20a85a028593190ea055e9143da28aa48c9ad1a1fa36a5200f8d084682e4d986

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
